// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project_2

#ifndef _SQUARELINE_PROJECT_2_UI_H
#define _SQUARELINE_PROJECT_2_UI_H

#ifdef __cplusplus
extern "C" {
#endif


#include "lvgl/lvgl.h"
#include <time.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <arpa/inet.h>
#include <signal.h>
#include <sys/ioctl.h>
#include <net/if.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <fcntl.h>

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label3;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label6;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label5;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Keyboard1;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label7;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label8;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Keyboard2;
void ui_event_TextArea4(lv_event_t * e);
extern lv_obj_t * ui_TextArea4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label9;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label10;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Label11;
void ui_event_TextArea5(lv_event_t * e);
extern lv_obj_t * ui_TextArea5;
extern lv_obj_t * ui_Keyboard3;
void ui_event_TextArea6(lv_event_t * e);
extern lv_obj_t * ui_TextArea6;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label12;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label19;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label20;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label21;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Image3;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label22;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Image6;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image9;
void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui____initial_actions0;

extern int bt13;
extern int light;
extern int light_c;

LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_803566317);    // assets/返回(1).png
LV_IMG_DECLARE(ui_img_209146575);    // assets/退出(5).png
LV_IMG_DECLARE(ui_img_221393495);    // assets/减号.png
LV_IMG_DECLARE(ui_img_1284172916);    // assets/加号.png
LV_IMG_DECLARE(ui_img_1119873443);    // assets/娱乐 (4).png
LV_IMG_DECLARE(ui_img_1021693127);    // assets/add-6.png
LV_IMG_DECLARE(ui_img_293610998);    // assets/add-3.png
LV_IMG_DECLARE(ui_img_1109815811);    // assets/add-4.png



LV_FONT_DECLARE(ui_font_HS4);
LV_FONT_DECLARE(ui_font_SuperHS1);
LV_FONT_DECLARE(ui_font_WeatherHS1);
LV_FONT_DECLARE(ui_font_WeatherHS2);


extern double temperture;
extern int humidity;
extern int aqi;

typedef struct time_c
{
    char date[20];
    char time[20];
} timeC;

typedef struct homeMsg
{
    char homeAqi[10];
    char homeTemp[10];
    char homeHum[10];

} hMsg;

typedef struct weather
{
    char weather[100];
    char temper[10];
} wMsg;

void * update_time_call();
void * update_time_pth();
void * update_info_call();
void * update_info_pth();
void * udp_tram_recv();
void * udp_recv_time();
void * udp_sent();
void * weather_update_call();
void * weather_update_pth();
void * change_led();
void *change_led_flash();

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
